// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using redrift.DB;

#nullable disable

namespace RedRift.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220522112650_Update1")]
    partial class Update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("redrift.DataClass.Lobby", b =>
                {
                    b.Property<uint>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Owner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("LobbyId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("redrift.DataClass.Match", b =>
                {
                    b.Property<uint>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerOneHP")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerOneId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerTwoHP")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerTwoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("redrift.DataClass.User", b =>
                {
                    b.Property<uint>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
